kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
    - hostPath: /home/arun/warzone/kind-storage
      containerPath: /host-storage
- role: worker
- role: worker
- role: worker
